baseURL : https://youngbai-c.github.io
languageCode : zh-cn
title : Young Bai
theme : PaperMod
math : true
ShowToc: true
publishDir : docs
menu : 
  main : 
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
